// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {XochiZKPVerifier} from "../src/XochiZKPVerifier.sol";
import {XochiZKPOracle} from "../src/XochiZKPOracle.sol";
import {IXochiZKPOracle} from "../src/interfaces/IXochiZKPOracle.sol";
import {ProofTypes} from "../src/libraries/ProofTypes.sol";

/// @title Integration tests using real UltraHonk proofs generated by bb
/// @notice These tests deploy the generated HonkVerifier contracts and verify
///         actual ZK proofs from the Noir circuits, end-to-end.
contract IntegrationTest is Test {
    XochiZKPVerifier internal verifier;
    XochiZKPOracle internal oracle;

    address internal owner = makeAddr("owner");
    address internal alice = makeAddr("alice");

    /// @dev Must match the config_hash baked into the compliance proof fixture.
    ///      This is pedersen_hash([100, 0, 0, 0, 0, 0, 0, 0]) -- the weight config
    ///      used in the test witness (single provider, weight=100).
    bytes32 internal constant FIXTURE_CONFIG_HASH = 0x18574f427f33c6c77af53be06544bd749c9a1db855599d950af61ea613df8405;

    /// @dev Must match the provider_set_hash baked into the compliance proof fixture.
    bytes32 internal constant FIXTURE_PROVIDER_SET_HASH =
        0x14b6becf762f80a24078e62fc9a7eca246b8e406d19962dda817b173f30a94b2;

    function setUp() public {
        verifier = new XochiZKPVerifier(owner);
        oracle = new XochiZKPOracle(address(verifier), owner, FIXTURE_CONFIG_HASH);

        // Deploy the generated compliance verifier and register it
        address complianceVerifier = _deployGeneratedVerifier("compliance");
        vm.prank(owner);
        verifier.setVerifier(ProofTypes.COMPLIANCE, complianceVerifier);
    }

    // -------------------------------------------------------------------------
    // End-to-end: real proof verification
    // -------------------------------------------------------------------------

    function test_realProof_compliance_verifies() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        bool valid = verifier.verifyProof(ProofTypes.COMPLIANCE, proof, publicInputs);
        assertTrue(valid);
    }

    function test_realProof_compliance_submitAndCheck() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        vm.prank(alice);
        IXochiZKPOracle.ComplianceAttestation memory att = oracle.submitCompliance(
            0, // jurisdiction EU (matches fixture)
            ProofTypes.COMPLIANCE,
            proof,
            publicInputs,
            FIXTURE_PROVIDER_SET_HASH
        );

        assertEq(att.subject, alice);
        assertEq(att.jurisdictionId, 0);
        assertTrue(att.meetsThreshold);
        assertEq(att.providerSetHash, FIXTURE_PROVIDER_SET_HASH);
        assertEq(att.verifierUsed, verifier.getVerifier(ProofTypes.COMPLIANCE));

        // checkCompliance should return valid
        (bool valid,) = oracle.checkCompliance(alice, 0);
        assertTrue(valid);

        // Historical proof should be retrievable
        IXochiZKPOracle.ComplianceAttestation memory historical =
            oracle.getHistoricalProof(keccak256(abi.encodePacked(proof, ProofTypes.COMPLIANCE)));
        assertEq(historical.subject, alice);
    }

    function test_realProof_compliance_replayReverts() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        vm.prank(alice);
        oracle.submitCompliance(0, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);

        // Same proof should be rejected
        vm.prank(alice);
        vm.expectRevert(
            abi.encodeWithSelector(
                XochiZKPOracle.ProofAlreadyUsed.selector, keccak256(abi.encodePacked(proof, ProofTypes.COMPLIANCE))
            )
        );
        oracle.submitCompliance(0, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);
    }

    function test_realProof_compliance_wrongJurisdictionReverts() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        // Fixture has jurisdiction_id=0 (EU), try submitting as US (1)
        vm.prank(alice);
        vm.expectRevert(XochiZKPOracle.PublicInputMismatch.selector);
        oracle.submitCompliance(1, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);
    }

    function test_realProof_compliance_corruptedProofFails() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        // Corrupt one byte of the proof
        proof[42] = proof[42] ^ 0xff;

        // Corrupted proof should revert (verifier reverts on invalid proofs)
        vm.prank(alice);
        vm.expectRevert();
        oracle.submitCompliance(0, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    function _loadFixture(string memory circuit) internal view returns (bytes memory proof, bytes memory publicInputs) {
        string memory proofPath = string.concat("test/fixtures/", circuit, "/proof");
        string memory inputsPath = string.concat("test/fixtures/", circuit, "/public_inputs");
        proof = vm.readFileBinary(proofPath);
        publicInputs = vm.readFileBinary(inputsPath);
    }

    function _deployGeneratedVerifier(string memory circuit) internal returns (address) {
        string memory contractName = _verifierContractName(circuit);
        string memory artifact = string.concat(circuit, "_verifier.sol:", contractName);
        bytes memory bytecode = vm.getCode(artifact);
        address deployed;
        assembly {
            deployed := create(0, add(bytecode, 0x20), mload(bytecode))
        }
        require(deployed != address(0), "verifier deployment failed");
        return deployed;
    }

    function _verifierContractName(string memory circuit) internal pure returns (string memory) {
        if (keccak256(bytes(circuit)) == keccak256("compliance")) return "ComplianceVerifier";
        if (keccak256(bytes(circuit)) == keccak256("risk_score")) return "RiskScoreVerifier";
        if (keccak256(bytes(circuit)) == keccak256("anti_structuring")) return "AntiStructuringVerifier";
        if (keccak256(bytes(circuit)) == keccak256("tier_verification")) return "TierVerificationVerifier";
        if (keccak256(bytes(circuit)) == keccak256("membership")) return "MembershipVerifier";
        if (keccak256(bytes(circuit)) == keccak256("non_membership")) return "NonMembershipVerifier";
        revert("unknown circuit");
    }
}
