// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.28;

import {IXochiZKPVerifier} from "./interfaces/IXochiZKPVerifier.sol";
import {IUltraVerifier} from "./interfaces/IUltraVerifier.sol";
import {ProofTypes} from "./libraries/ProofTypes.sol";

/// @title XochiZKPVerifier -- Reference implementation of the Xochi ZKP verifier
/// @notice Routes proof verification to per-proof-type UltraHonk verifier contracts
/// @dev Each proof type maps to a separate Noir circuit with its own generated verifier.
///      Verifier contracts are generated by Barretenberg (`bb contract`) from compiled circuits.
contract XochiZKPVerifier is IXochiZKPVerifier {
    /// @notice Owner who can update verifier addresses
    address public owner;

    /// @notice Pending owner for two-step transfer
    address public pendingOwner;

    /// @notice Deadline for pending owner to accept (48 hours from initiation)
    uint256 internal _ownershipTransferDeadline;

    /// @notice Mapping from proof type ID to its UltraHonk verifier contract
    mapping(uint8 proofType => address verifier) internal _verifiers;

    /// @notice Append-only history of verifier addresses per proof type
    mapping(uint8 proofType => address[] history) internal _verifierHistory;

    error Unauthorized();
    error NotPendingOwner();
    error ZeroAddress();
    error VerifierNotSet(uint8 proofType);
    error InvalidVersion(uint8 proofType, uint256 version);
    error BatchLengthMismatch();
    error EmptyBatch();
    error OwnershipTransferExpired();

    event VerifierUpdated(uint8 indexed proofType, address indexed oldVerifier, address indexed newVerifier);
    event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    constructor(address initialOwner) {
        if (initialOwner == address(0)) revert ZeroAddress();
        owner = initialOwner;
        emit OwnershipTransferred(address(0), initialOwner);
    }

    // -------------------------------------------------------------------------
    // IXochiZKPVerifier
    // -------------------------------------------------------------------------

    /// @inheritdoc IXochiZKPVerifier
    function verifyProof(uint8 proofType, bytes calldata proof, bytes calldata publicInputs)
        external
        view
        returns (bool valid)
    {
        return _verify(proofType, proof, publicInputs);
    }

    /// @inheritdoc IXochiZKPVerifier
    function verifyProofBatch(uint8[] calldata proofTypes, bytes[] calldata proofs, bytes[] calldata publicInputs)
        external
        view
        returns (bool valid)
    {
        uint256 length = proofTypes.length;
        if (length == 0) revert EmptyBatch();
        if (length != proofs.length || length != publicInputs.length) revert BatchLengthMismatch();

        for (uint256 i; i < length;) {
            if (!_verify(proofTypes[i], proofs[i], publicInputs[i])) {
                return false;
            }
            unchecked {
                ++i;
            }
        }
        return true;
    }

    /// @inheritdoc IXochiZKPVerifier
    function getVerifier(uint8 proofType) external view returns (address verifier) {
        return _verifiers[proofType];
    }

    /// @inheritdoc IXochiZKPVerifier
    function verifyProofAtVersion(uint8 proofType, uint256 version, bytes calldata proof, bytes calldata publicInputs)
        external
        view
        returns (bool valid)
    {
        address verifier = _getVerifierAtVersion(proofType, version);
        ProofTypes.validatePublicInputs(proofType, publicInputs);
        bytes32[] memory inputs = ProofTypes.decodePublicInputs(publicInputs);
        return IUltraVerifier(verifier).verify(proof, inputs);
    }

    /// @inheritdoc IXochiZKPVerifier
    function getVerifierAtVersion(uint8 proofType, uint256 version) external view returns (address verifier) {
        return _getVerifierAtVersion(proofType, version);
    }

    /// @inheritdoc IXochiZKPVerifier
    function getVerifierVersion(uint8 proofType) external view returns (uint256 version) {
        return _verifierHistory[proofType].length;
    }

    // -------------------------------------------------------------------------
    // Admin
    // -------------------------------------------------------------------------

    /// @notice Set or update the verifier contract for a proof type
    /// @param proofType The proof type (0x01-0x06)
    /// @param verifier The UltraHonk verifier contract address
    function setVerifier(uint8 proofType, address verifier) external onlyOwner {
        if (!ProofTypes.isValidProofType(proofType)) revert ProofTypes.InvalidProofType(proofType);
        if (verifier == address(0)) revert ZeroAddress();

        address old = _verifiers[proofType];
        _verifiers[proofType] = verifier;
        _verifierHistory[proofType].push(verifier);
        emit VerifierUpdated(proofType, old, verifier);
    }

    /// @notice Begin two-step ownership transfer (48 hour acceptance window)
    /// @param newOwner The address to transfer ownership to
    function transferOwnership(address newOwner) external onlyOwner {
        if (newOwner == address(0)) revert ZeroAddress();
        pendingOwner = newOwner;
        _ownershipTransferDeadline = block.timestamp + 48 hours;
        emit OwnershipTransferStarted(owner, newOwner);
    }

    /// @notice Accept ownership transfer (must be within 48 hours of initiation)
    function acceptOwnership() external {
        if (msg.sender != pendingOwner) revert NotPendingOwner();
        if (block.timestamp > _ownershipTransferDeadline) revert OwnershipTransferExpired();
        address old = owner;
        owner = msg.sender;
        pendingOwner = address(0);
        _ownershipTransferDeadline = 0;
        emit OwnershipTransferred(old, msg.sender);
    }

    // -------------------------------------------------------------------------
    // Internal
    // -------------------------------------------------------------------------

    /// @dev Verify a single proof by routing to the appropriate UltraHonk verifier
    function _verify(uint8 proofType, bytes calldata proof, bytes calldata publicInputs)
        internal
        view
        returns (bool valid)
    {
        if (!ProofTypes.isValidProofType(proofType)) revert ProofTypes.InvalidProofType(proofType);

        address verifier = _verifiers[proofType];
        if (verifier == address(0)) revert VerifierNotSet(proofType);

        ProofTypes.validatePublicInputs(proofType, publicInputs);

        bytes32[] memory inputs = ProofTypes.decodePublicInputs(publicInputs);
        return IUltraVerifier(verifier).verify(proof, inputs);
    }

    /// @dev Resolve a verifier address from the version history (1-indexed)
    function _getVerifierAtVersion(uint8 proofType, uint256 version) internal view returns (address verifier) {
        address[] storage history = _verifierHistory[proofType];
        if (version == 0 || version > history.length) {
            revert InvalidVersion(proofType, version);
        }
        return history[version - 1];
    }
}
