// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.28;

import {IXochiZKPVerifier} from "./interfaces/IXochiZKPVerifier.sol";
import {IUltraVerifier} from "./interfaces/IUltraVerifier.sol";
import {ProofTypes} from "./libraries/ProofTypes.sol";
import {Ownable2Step} from "./libraries/Ownable2Step.sol";
import {Pausable} from "./libraries/Pausable.sol";

/// @title XochiZKPVerifier -- Reference implementation of the Xochi ZKP verifier
/// @notice Routes proof verification to per-proof-type UltraHonk verifier contracts
/// @dev Each proof type maps to a separate Noir circuit with its own generated verifier.
///      Verifier contracts are generated by Barretenberg (`bb contract`) from compiled circuits.
contract XochiZKPVerifier is IXochiZKPVerifier, Ownable2Step, Pausable {
    /// @notice Mapping from proof type ID to its UltraHonk verifier contract
    mapping(uint8 proofType => address verifier) internal _verifiers;

    /// @notice Append-only history of verifier addresses per proof type
    mapping(uint8 proofType => address[] history) internal _verifierHistory;

    /// @notice Pending verifier proposals per proof type
    mapping(uint8 proofType => VerifierProposal proposal) internal _pendingVerifiers;

    struct VerifierProposal {
        address newVerifier;
        uint256 proposedAt;
    }

    error VerifierNotSet(uint8 proofType);
    error VerifierAlreadySet(uint8 proofType);
    error InvalidVersion(uint8 proofType, uint256 version);
    error TimelockNotElapsed(uint8 proofType, uint256 readyAt);
    error NoPendingProposal(uint8 proofType);
    error ProposalAlreadyPending(uint8 proofType);
    error BatchLengthMismatch();
    error EmptyBatch();
    error BatchTooLarge();

    /// @notice Maximum number of proofs in a single batch verification
    uint256 public constant MAX_BATCH_SIZE = 100;

    /// @notice Delay before a proposed verifier can be executed
    uint256 public constant VERIFIER_TIMELOCK = 24 hours;

    event VerifierUpdated(uint8 indexed proofType, address indexed oldVerifier, address indexed newVerifier);
    event VerifierProposed(uint8 indexed proofType, address indexed newVerifier, uint256 readyAt);
    event VerifierProposalCancelled(uint8 indexed proofType, address indexed cancelledVerifier);

    constructor(address initialOwner) {
        if (initialOwner == address(0)) revert ZeroAddress();
        owner = initialOwner;
        emit OwnershipTransferred(address(0), initialOwner);
    }

    // -------------------------------------------------------------------------
    // IXochiZKPVerifier
    // -------------------------------------------------------------------------

    /// @inheritdoc IXochiZKPVerifier
    function verifyProof(uint8 proofType, bytes calldata proof, bytes calldata publicInputs)
        external
        view
        whenNotPaused
        returns (bool valid)
    {
        return _verify(proofType, proof, publicInputs);
    }

    /// @inheritdoc IXochiZKPVerifier
    function verifyProofBatch(uint8[] calldata proofTypes, bytes[] calldata proofs, bytes[] calldata publicInputs)
        external
        view
        whenNotPaused
        returns (bool valid)
    {
        uint256 length = proofTypes.length;
        if (length == 0) revert EmptyBatch();
        if (length > MAX_BATCH_SIZE) revert BatchTooLarge();
        if (length != proofs.length || length != publicInputs.length) revert BatchLengthMismatch();

        for (uint256 i; i < length;) {
            if (!_verify(proofTypes[i], proofs[i], publicInputs[i])) {
                return false;
            }
            unchecked {
                ++i;
            }
        }
        return true;
    }

    /// @inheritdoc IXochiZKPVerifier
    function getVerifier(uint8 proofType) external view returns (address verifier) {
        return _verifiers[proofType];
    }

    /// @inheritdoc IXochiZKPVerifier
    function verifyProofAtVersion(uint8 proofType, uint256 version, bytes calldata proof, bytes calldata publicInputs)
        external
        view
        whenNotPaused
        returns (bool valid)
    {
        address verifier = _getVerifierAtVersion(proofType, version);
        ProofTypes.validatePublicInputs(proofType, publicInputs);
        bytes32[] memory inputs = ProofTypes.decodePublicInputs(publicInputs);
        return IUltraVerifier(verifier).verify(proof, inputs);
    }

    /// @inheritdoc IXochiZKPVerifier
    function getVerifierAtVersion(uint8 proofType, uint256 version) external view returns (address verifier) {
        return _getVerifierAtVersion(proofType, version);
    }

    /// @inheritdoc IXochiZKPVerifier
    function getVerifierVersion(uint8 proofType) external view returns (uint256 version) {
        return _verifierHistory[proofType].length;
    }

    // -------------------------------------------------------------------------
    // Admin
    // -------------------------------------------------------------------------

    /// @notice Set verifier for initial deployment only (no timelock)
    /// @dev Reverts if a verifier is already set for this proof type.
    ///      Use proposeVerifier + executeVerifierUpdate for subsequent changes.
    /// @param proofType The proof type (0x01-0x06)
    /// @param verifier The UltraHonk verifier contract address
    function setVerifierInitial(uint8 proofType, address verifier) external onlyOwner {
        if (!ProofTypes.isValidProofType(proofType)) revert ProofTypes.InvalidProofType(proofType);
        if (verifier == address(0)) revert ZeroAddress();
        if (_verifiers[proofType] != address(0)) revert VerifierAlreadySet(proofType);

        _verifiers[proofType] = verifier;
        _verifierHistory[proofType].push(verifier);
        emit VerifierUpdated(proofType, address(0), verifier);
    }

    /// @notice Propose a new verifier for a proof type (starts timelock)
    /// @param proofType The proof type (0x01-0x06)
    /// @param newVerifier The proposed UltraHonk verifier contract address
    function proposeVerifier(uint8 proofType, address newVerifier) external onlyOwner {
        if (!ProofTypes.isValidProofType(proofType)) revert ProofTypes.InvalidProofType(proofType);
        if (newVerifier == address(0)) revert ZeroAddress();
        if (_pendingVerifiers[proofType].proposedAt != 0) revert ProposalAlreadyPending(proofType);

        _pendingVerifiers[proofType] = VerifierProposal({newVerifier: newVerifier, proposedAt: block.timestamp});

        uint256 readyAt = block.timestamp + VERIFIER_TIMELOCK;
        emit VerifierProposed(proofType, newVerifier, readyAt);
    }

    /// @notice Execute a pending verifier update after the timelock has elapsed
    /// @param proofType The proof type (0x01-0x06)
    function executeVerifierUpdate(uint8 proofType) external onlyOwner {
        VerifierProposal memory proposal = _pendingVerifiers[proofType];
        if (proposal.proposedAt == 0) revert NoPendingProposal(proofType);

        uint256 readyAt = proposal.proposedAt + VERIFIER_TIMELOCK;
        if (block.timestamp < readyAt) revert TimelockNotElapsed(proofType, readyAt);

        address old = _verifiers[proofType];
        _verifiers[proofType] = proposal.newVerifier;
        _verifierHistory[proofType].push(proposal.newVerifier);
        delete _pendingVerifiers[proofType];

        emit VerifierUpdated(proofType, old, proposal.newVerifier);
    }

    /// @notice Cancel a pending verifier proposal
    /// @param proofType The proof type (0x01-0x06)
    function cancelVerifierProposal(uint8 proofType) external onlyOwner {
        VerifierProposal memory proposal = _pendingVerifiers[proofType];
        if (proposal.proposedAt == 0) revert NoPendingProposal(proofType);

        delete _pendingVerifiers[proofType];
        emit VerifierProposalCancelled(proofType, proposal.newVerifier);
    }

    /// @notice Get the pending verifier proposal for a proof type
    /// @param proofType The proof type
    /// @return newVerifier The proposed verifier address (address(0) if none)
    /// @return readyAt The timestamp when the proposal can be executed (0 if none)
    function getPendingVerifier(uint8 proofType) external view returns (address newVerifier, uint256 readyAt) {
        VerifierProposal memory proposal = _pendingVerifiers[proofType];
        if (proposal.proposedAt == 0) return (address(0), 0);
        return (proposal.newVerifier, proposal.proposedAt + VERIFIER_TIMELOCK);
    }

    /// @notice Pause the contract, blocking proof verification
    function pause() external override onlyOwner {
        if (paused) revert ContractPaused();
        paused = true;
        emit Paused(msg.sender);
    }

    /// @notice Unpause the contract, resuming proof verification
    function unpause() external override onlyOwner {
        if (!paused) revert ContractNotPaused();
        paused = false;
        emit Unpaused(msg.sender);
    }

    // -------------------------------------------------------------------------
    // Internal
    // -------------------------------------------------------------------------

    /// @dev Verify a single proof by routing to the appropriate UltraHonk verifier
    function _verify(uint8 proofType, bytes calldata proof, bytes calldata publicInputs)
        internal
        view
        returns (bool valid)
    {
        if (!ProofTypes.isValidProofType(proofType)) revert ProofTypes.InvalidProofType(proofType);

        address verifier = _verifiers[proofType];
        if (verifier == address(0)) revert VerifierNotSet(proofType);

        ProofTypes.validatePublicInputs(proofType, publicInputs);

        bytes32[] memory inputs = ProofTypes.decodePublicInputs(publicInputs);
        return IUltraVerifier(verifier).verify(proof, inputs);
    }

    /// @dev Resolve a verifier address from the version history (1-indexed)
    function _getVerifierAtVersion(uint8 proofType, uint256 version) internal view returns (address verifier) {
        address[] storage history = _verifierHistory[proofType];
        if (version == 0 || version > history.length) {
            revert InvalidVersion(proofType, version);
        }
        return history[version - 1];
    }
}
